chore: downgrade kpt version to fix e2e test.
This is necessary because with kpt >1.0.0-beta.20 the kpt e2e tests that use "os/user".Current() fail with kpt panicing:
```
   fatal error: unexpected signal during runtime execution
   [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f8370554ef4]

   runtime stack:
   runtime.throw({0x28bf079?, 0x0?})
   	/usr/local/go/src/runtime/panic.go:992 +0x71
   runtime.sigpanic()
   	/usr/local/go/src/runtime/signal_unix.go:802 +0x3a9

   goroutine 1 [syscall]:
   runtime.cgocall(0x19a9630, 0xc002606c70)
   	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc002606c48 sp=0xc002606c10 pc=0x44f21c
   os/user._Cfunc_mygetpwuid_r(0x3e8, 0xc00186bf50, 0x51215d0, 0x400, 0xc000010380)
   	_cgo_gotypes.go:175 +0x4c fp=0xc002606c70 sp=0xc002606c48 pc=0xa5b44c
   os/user.lookupUnixUid.func1.1(0x3e8, 0x3e647a0?, 0xc002606d08?, 0x459247?)
   	/usr/local/go/src/os/user/cgo_lookup_unix.go:102 +0xa6 fp=0xc002606cd0 sp=0xc002606c70 pc=0xa5bfc6
```